IMAGE_NAME = "bento/ubuntu-18.04"

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false
    config.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 2
    end
    config.vm.define "RedisVm" do |master|
		master.vm.box = IMAGE_NAME
        master.vm.network "private_network", ip: "172.28.128.12"
        master.vm.hostname = "redis"
		master.vm.provision "ansible_local" do |ansible|
            ansible.playbook = "redis-playbook.yaml"
			ansible.version = '2.9.15'
         end
  
     end
end